server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

openai:
  model: gpt-3.5-turbo
  api:
    key: sk-proj-VDRNELmt2UKXS6ZzpeuST3BlbkFJpQRXRPhyip6xiZRrF5qt
    url: https://api.openai.com/v1/chat/completions


